name: Test Extension
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: main

env:
  API_URL: https://api.samepage.network
  AWS_ACCESS_KEY_ID: ${{ secrets.SAMEPAGE_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SAMEPAGE_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  NOTION_INTEGRATION_TOKEN: ${{ secrets.NOTION_TEST_INTEGRATION_TOKEN }}
  NOTION_TEST_PASSWORD: ${{ secrets.NOTION_TEST_PASSWORD }}
  PLAYWRIGHT_HTML_REPORT: playwright-report
  SAMEPAGE_TEST_PASSWORD: ${{ secrets.SAMEPAGE_TEST_PASSWORD }}
  WEB_SOCKET_URL: wss://ws.samepage.network

jobs:
  test-mac:
    # runs-on: ubuntu-latest - TODO instead of reintroducing, we could look into matrixing. Seems low value, high cost tho
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: install playwright
        run: npx playwright install
      - name: test
        run: node scripts/test.js
      - name: Upload Integration Test Coverage to Codecov
        uses: codecov/codecov-action@v3
